[build]
  command = "echo 'default context'"
[functions]
  external_node_modules = ["express"]
  node_bundler = "webpack"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
